version: 2
registries:
  private-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/IngridTPires/index.json
    token: ${{secrets.MY_PACKAGE_TOKEN}}
  nuget-packages:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries: "*"
    schedule:
      interval: "daily"    
    open-pull-requests-limit: 10
    reviewers: 
      - "ingridTPires"
    commit-message:
      prefix: "chore"
      include: "scope"
    target-branch: "main"
    allow:
      - dependency-name: "Z.EntityFramework.Extensions"
    ignore:
      - dependency-name: "Newtonsoft.Json"
      - dependency-name: "NuGetPackage"